language: php
php:
  - '7.2'

install:
  - composer install
  - pecl install ast

script:
  - composer coverage
  - composer lint
  - composer md
  - composer analyze

after_success:
  - bash <(curl -s https://codecov.io/bash)
